### ISSUE TITLE
Would it be possible to add the legend to any of your dashing chart.js widgets?

### ISSUE THREAD

**Issue by enriquemt** [jorgemorgado/dashing-piechart#1]
I am trying to add the legend to any of your dashing chart.js widgets, is that possible?

I am wondering if it is also possible to keep the Labels of the series always on the screen.

Thanks in advance.

**Comment by jorgemorgado** [comment]
Have a look at this [similar request](https://github.com/jorgemorgado/dashing-doughnutchart/issues/2). Like I wrote there, if you implement something in that direction, send me a pull request.

**Comment by enriquemt** [comment]
Dear jorge, I rewrote the widget pie chart in order to use legend. I'm afraid it is not a very elegant implementation however it covers what I needed.

If you are interested I can send it to you.

Best regards

**Comment by jorgemorgado** [comment]
Hi @enriquemt. Thank you for your effort. Sure, either send a pull request or send me the code/install details to jorge+github-dashing-piechart@morgado.ch

**Comment by jorgemorgado** [comment]
I've just released the new version with support for Chart.js v2. In this version, the legend is enabled by default.
